# Generated by Django 5.1.4 on 2025-12-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=8, unique=True)),
                ('players', models.JSONField(default=list)),
                ('imposter', models.CharField(blank=True, max_length=50)),
                ('word', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
