# Generated by Django 5.1.4 on 2026-01-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imposterGame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='imposter',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='imposter',
            field=models.ManyToManyField(blank=True, related_name='imposter_in_rooms', to='imposterGame.player'),
        ),
    ]
