# Generated by Django 5.1.4 on 2026-01-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imposterGame', '0002_remove_room_imposter_alter_room_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(unique=True),
        ),
    ]
